import { StyleSheet, Dimensions } from 'react-native';
import { backgroundColor, textColor } from '../../constants/const_strings';
const { width, height } = Dimensions.get('window');
export default StyleSheet.create({
    containerBackground:{
        backgroundColor:'#F9FAFC',
        width:'100%'
    },
    cardContainer:{
        margin:20,
        backgroundColor:'#FFFFFF',
        height:150
    },
    cardCover:{
        margin:20
    },
    cardHeaderRow:{
        flexDirection:'row',
    },
    cartImage:{
        height:70,
        width:70,
        borderRadius:5
    },
    cardItemName:{
        margin:5,
        marginLeft:15,
        fontSize:18
    },
    cardItemPrice:{
        marginLeft:15,
        fontSize:18,
        fontWeight:'bold'
    },
    cardBreak:{
        width:'100%',
        height:2,
        marginTop:10,
        backgroundColor:'#F6F2F2'
    },
    cardFooterRow:{
        marginTop:5,
        flexDirection:'row',
        justifyContent: 'space-between',
    },
    deleteRow:{
        flexDirection:'row',
    },
    deleteRowText:{
        margin:4,
        fontSize:15
    },
    quantityRow:{
        flexDirection:'row',
        justifyContent:'space-between'
    },
    quantityCover:{
        borderColor:'#123CD3',
        borderWidth:1,
        height:30,
        width:30,
        borderRadius:30/2,
        justifyContent:'center',
        alignItems:'center'
    },
    quantity:{
        color:'#123CD3',

    },
    quantityText:{
        marginLeft:10,
        marginRight:10,
        marginTop:5
    },
    checkoutCardContainer:{
        width:'100%',
        height:200,
    },
    checkoutCardWrapper:{
        margin:20
    },
    subTotalRow:{
        flexDirection:'row',
        justifyContent:'space-between',
    },
    totalText:{
        fontSize:15
    },
    checkoutButton:{
        height:60,
        width:'100%',
        backgroundColor:'#227EFF',
        marginTop:20,
        alignItems:'center',
        justifyContent:'center',
        borderRadius:5
    },
    checkoutText:{
        color:'#fff',
        fontSize:18,
        fontWeight:'bold'
    },
    lineBreak:{
        width:'100%',
        height:8,
        backgroundColor:'#F9FAFC'
    },
    recentlyViewText:{
        fontSize:16,
    },
    viewAllText:{
        color:'#227EFF',
        fontSize:16
    },
    productItemsContainer:{
        flexDirection:'row',
        justifyContent:'space-between',
        flexWrap:'wrap',
        margin:20,
        flex:1,
        alignItems:'flex-start'
    },
});